version: "3"
services:
  mongo:
    build: ./mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=password
    - MONGO_INITDB_DATABASE=mydb
    volumes:
    - mongo-data:/data/db
    networks:
    - developing
volumes:
  mongo-data:
    driver: local
networks:
  developing:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.20.30.0/24